// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`Issue #26 given InternalServerError exception and custom exception sharing the same status code should attach the exceptions properly without missing another 1`] = `
{
  "500": {
    "content": {
      "application/json": {
        "examples": {
          "EmailResponseFailedException": {
            "description": "Email Response Failed",
            "value": {
              "error": "Internal Server Error",
              "message": "Email Response Failed",
              "statusCode": 500,
            },
          },
          "InternalServerException": {
            "description": "Something went wrong",
            "value": {
              "error": "Internal Server Error",
              "message": "Something went wrong",
              "statusCode": 500,
            },
          },
        },
        "schema": {
          "description": undefined,
          "properties": {
            "error": {
              "example": "Internal Server Error",
              "type": "string",
            },
            "message": {
              "example": "Email Response Failed",
              "type": "string",
            },
            "statusCode": {
              "example": 500,
              "type": "number",
            },
          },
          "required": [
            "statusCode",
            "message",
          ],
          "type": "object",
        },
      },
    },
    "description": "",
    "isArray": undefined,
    "type": undefined,
  },
}
`;
